Add API
clarify/aquagraph_clarify pull request #1
Opened 2022-03-11 14:19 UTC by AlexiaArtemis

2022-03-14 09:33 UTC, oddaspa requested changes
Good stuff! I will add my part today. There are some typos in the readme. The file `precess_items_2.py` is a typo as well. I don't understand why we need two process_item files? What is the difference? There are also some debug prints in the code.

2022-03-14 09:33 UTC, oddaspa commented on README.md
> +Steps: Press Download. Add credentials. Click download desktop. Copy the activation key. Click and drag Neo4j Desktop to the Application folder. Open the Noe4j Desktop (go to Security & Privacy and c
Typo: _Noe4j_

2022-03-14 09:33 UTC, oddaspa commented on README.md
> +1. Make sure the Neo4j database is actived.
Typo: _activated_

2022-03-14 09:33 UTC, oddaspa commented on README.md
> +2. cd to aquagraph_arrows
No folder named _aquagraph_arrows_

2022-03-14 09:33 UTC, oddaspa commented on requirements.txt
> +uvicorn
missing dependency _dotenv_

2022-03-14 09:33 UTC, oddaspa commented on requirements.txt
> +uvicorn
using `python3 -m uvicorn main:app --port 8080 --reload` resolves missing dependency

2022-03-14 09:33 UTC, oddaspa commented on README.md
> +4. Go to http://localhost:8000/docs
Wrong port (use 8080 instead)

2022-03-15 11:40 UTC, AlexiaArtemis commented on requirements.txt
> +uvicorn
added dotenv in requirements.txt

2022-03-15 12:51 UTC, oddaspa approved these changes

2022-03-18 10:44 UTC, zehsilva approved these changes
Good work!

2022-03-18 10:50 UTC, merged